[package]
name = "cli_util"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli_util"  
path = "src/main.rs"          

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["cargo"] }
file-owner = "0.1.2"
humansize = "2.1.3"